#include "ComputeGroup.hlsli"

#define VALID_LENGTH_SQUARED_THRESHOLD 0.25

#define SMOOTH_RADIUS 4
#define SMOOTH_TILE_SIZE 16
#define SMOOTH_TILE_COUNT 256
#define SMOOTH_SPACE_TABLE_STRIDE 9
#define SMOOTH_SPACE_TABLE_COUNT 81
