#define GROUP_X 8
#define GROUP_Y 8
#define GROUP_Z 1
#define GROUP_THREADS (GROUP_X * GROUP_Y * GROUP_Z)

#define VALID_LENGTH_SQUARED_THRESHOLD 0.25

#define SMOOTH_RADIUS 4
#define SMOOTH_TILE_SIZE 16
#define SMOOTH_TILE_COUNT 256
#define SMOOTH_SPACE_TABLE_STRIDE 9
#define SMOOTH_SPACE_TABLE_COUNT 81
